### ISSUE TITLE
Roadmap for release of rework

### ISSUE THREAD

**Issue by AlphaKretin** [AlphaKretin/bastion-bot#34]
To try and motivate myself to get this thing released some time this decade (editor's note: RIP, but I have an excuse), I'm going to keep a big public list of what I need and/or plan to do to keep myself honest.

## Important Changes and Fixes
- [x] Loading order issues (https://github.com/AlphaKretin/ygo-data/issues/3)
- [x] Fix inconsistent reaction button errors (#36, https://github.com/AlphaKretin/bastion-bot/commit/0949a4b503c7fec715c506f6a88e269b8a3714cf)
- [x] Make config (and stats) use a real database instead of JSON
- [ ] Rework live-command/self-update system (#37)
- [ ] Rework permission system (#38)
- [x] Fix new Bastion not ignoring code blocks (#42)
- [x] Fix error with image-mobile view when no image exists (#41)
- [x] Add proper help command, including per-command help (#44)
- [x] Write documentation
- [x] Fix how "D/D" works with filters (https://github.com/AlphaKretin/ygo-data/commit/c0814c434dc00840bebd93aaa4074be869fba34b)
- [x] Add options to not see anime/custom cards, on by default (https://github.com/AlphaKretin/ygo-data/commit/e48431e7c3b6bc387f456dd4baa9aa3032c561a2, https://github.com/AlphaKretin/bastion-bot/commit/9339becb0e82f925da60c33c871a3eafcfc810bd)
- [x] Add missing "commands" command (https://github.com/AlphaKretin/bastion-bot/commit/68f12533c5e621455b90d2dafcd8341d3f8baf13)
- [x] Cards with permanent alias (e.g. Pacifis) are excluded from search results (https://github.com/AlphaKretin/bastion-bot/commit/bee790d2b6af01a33ca57fa98a31a5a27e808329)

## Non-critical, but ideally before release
- [x] Improve pendulum handling (https://github.com/AlphaKretin/ygo-data/issues/7, https://github.com/AlphaKretin/ygo-data/pull/6)
- [x] Add back non-reaction `.viewmatch`, and add `.matchpage` (#36, #43)
- [x] Update type/attribute emoji with cleaner versions I've been provided
- [x] Port over shortcuts from old Bastion
- [x] Reimplement recording stats on card searches, command use, etc.
- [ ] Rework name fuzzy search (https://github.com/AlphaKretin/ygo-data/issues/8)
- [x] Add response for 0-result search (https://github.com/AlphaKretin/bastion-bot/commit/a5a905c2194051643cb2d054e533f397208bc86f)
- [x] Stifle error spam when using `.mp` and the like in DMs (#46, https://github.com/AlphaKretin/bastion-bot/commit/c157018b338de457f9cf3f6b584a4d8e7abc5e70)
- [ ] Improve the inconsistent performance of reaction buttons (unrelated to above)
- [ ] Double check use of categories in filters
- [ ] Make scripting library search bidirectional

## "Nice-to-have"s and minor improvements
- [ ] Add Japanese wiki search (#40)
- [ ] Double-check handling of dashes and other characters in Trivia
- [ ] Filter searches by banlist status
- [ ] Dedicated `.price` command with expanded details
- [ ] Search scripts by name (for utility and similar)
- [ ] Specify which of name and card text user wants to search
- [ ] Combine name matches and text searches
- [ ] Narrow down already-existing searches with new additional filters
- [x] Add command to print invite link
- [x] Improve performance of many-result search
- [ ] Filter for cards without any archetype
- [ ] Show only name, effect, and/or stats in `.randcard`
- [ ] Command to search for card strings

**Comment by AlphaKretin** [comment]
One down! Loading order issues fixed by https://github.com/AlphaKretin/ygo-data/pull/4

**Comment by AlphaKretin** [comment]
Zero down... loading order isn't as fixed as it seemed

**Comment by AlphaKretin** [comment]
No, it is fixed, `npm install` just didn't actually update it on Bastion. Thanks, npm!

**Comment by AlphaKretin** [comment]
Missing image error fixed in #41

**Comment by AlphaKretin** [comment]
Code block ignoring fixed in #42. That was embarrassingly simple

**Comment by AlphaKretin** [comment]
The commands for `.viewmatch` and what I then called `.matchpage`, now `.md` and `.mp`, were added in #43.

**Comment by AlphaKretin** [comment]
Re: `Double check how "D/D" works with filters`, it does what I feared and filters for 2 non-existent archetypes called "D", so now that's `Fix how "D/D works with filters`.

**Comment by AlphaKretin** [comment]
"Stifle error spam when using .mp and the like in DMs" was achieved by merging #46 and committing https://github.com/AlphaKretin/bastion-bot/commit/c157018b338de457f9cf3f6b584a4d8e7abc5e70.

**Comment by AlphaKretin** [comment]
Bumping the importance of using databases for persistent storage since if I do want to do that I should probably do it before implementing other features that will use persistent storage, like permissions

**Comment by AlphaKretin** [comment]
Barring some mistake, the D/D issue should be fixed in https://github.com/AlphaKretin/ygo-data/commit/c0814c434dc00840bebd93aaa4074be869fba34b.

**Comment by AlphaKretin** [comment]
The rework has already been released in its current state and all of these need to be spun off into their own issues
